apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
  namespace: load-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
      - name: locust-master
        image: locustio/locust:2.29.1
        args: ["-f", "/mnt/locust/locustfile.py", "--master"]
        ports:
        - containerPort: 8089
        - containerPort: 5557
        - containerPort: 5558
        volumeMounts:
        - name: locustfile
          mountPath: /mnt/locust
        env:
        - name: LOCUST_LOG_LEVEL
          value: "INFO"
      volumes:
      - name: locustfile
        configMap:
          name: locustfile
---
apiVersion: v1
kind: Service
metadata:
  name: locust-master
  namespace: load-test
spec:
  selector:
    app: locust-master
  ports:
  - name: web
    port: 8089
    targetPort: 8089
  - name: master
    port: 5557
    targetPort: 5557
  - name: master-alt
    port: 5558
    targetPort: 5558
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: locust-master-web
  namespace: load-test
spec:
  selector:
    app: locust-master
  ports:
  - port: 8089
    targetPort: 8089
  type: LoadBalancer