apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: prod
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk  # base64-encoded "rootpassword"
  mysql-user: d29yZHByZXNz  # base64-encoded "wordpress"
  mysql-password: d29yZHByZXNzcGFzc3dvcmQ=  # base64-encoded "wordpresspassword"
  mysql-database: d29yZHByZXNz  # base64-encoded "wordpress"