apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: dev
spec:
  selector:
    app: echoserver
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
  type: NodePort