apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: prod
  name: prod-edit-binding
subjects:
- kind: User
  name: derrick.weil@gmail.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: prod-edit
  apiGroup: rbac.authorization.k8s.io